[package]
authors = ["Kuaishou AI Platform PersiaML Team <zhuxuefeng@kuaishou.com>"]
edition = "2018"
license = "MIT"
name = "persia-storage-visitor"
publish = false
version = "0.1.0"

[dependencies]
persia-common = {path = "../persia-common"}
persia-libs = {path = "../persia-libs"}
persia-speedy = "0.9"
