[package]
authors = ["Kuaishou AI Platform PersiaML Team <zhuxuefeng@mkuaishou.com>"]
edition = "2018"
license = "MIT"
name = "persia-metrics"
version = "0.1.0"

[dependencies]
persia-embedding-config = {path = "../persia-embedding-config"}
persia-libs = {path = "../persia-libs"}
prometheus = {version = "0.13.0", features = ["push"]}
prometheus_exporter = "0.8.2"
scheduled-thread-pool = "0.2"
