[package]
authors = ["Kuaishou AI Platform PersiaML Team <zhuxuefeng@kuaishou.com>"]
edition = "2018"
license = "MIT"
name = "persia-nats-marcos"
publish = false
version = "0.1.0"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0.78"

[lib]
proc-macro = true
